wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1727947382.981371
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.9.0
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
