wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1683014151.530053
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.9.0
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
alias:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 1000
cache_eval:
  desc: null
  value: null
dataset:
  desc: null
  value: Jet_Engine
decay1:
  desc: null
  value: 0.9
decay2:
  desc: null
  value: 0.999
device:
  desc: null
  value: cpu
dropout:
  desc: null
  value: 0
experiment_id:
  desc: null
  value: ''
init:
  desc: null
  value: 0.001
learning_rate:
  desc: null
  value: 0.1
lmbda:
  desc: null
  value: 0.05
loss:
  desc: null
  value: CrossEntropyLoss()
max_epochs:
  desc: null
  value: 100
model:
  desc: null
  value: RESCAL
model_cache_path:
  desc: null
  value: null
num_neg:
  desc: null
  value: 0
optimizer:
  desc: null
  value: Adagrad
rank:
  desc: null
  value: 1000
rank_r:
  desc: null
  value: 100
reciprocal:
  desc: null
  value: true
regularizer:
  desc: null
  value: N3
run_notes:
  desc: null
  value: ''
run_tags:
  desc: null
  value: []
score_lhs:
  desc: null
  value: false
score_rel:
  desc: null
  value: true
score_rhs:
  desc: null
  value: true
seed:
  desc: null
  value: 0
size:
  desc: null
  value:
  - 486
  - 124
  - 486
valid:
  desc: null
  value: 3
w_lhs:
  desc: null
  value: 1
w_rel:
  desc: null
  value: 4.0
world:
  desc: null
  value: LCWA
